services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: cccat
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql