ktor:
    application:
        modules:
            - com.example.infra.ApplicationKt.module
    deployment:
        port: 8080
    database:
        driverClassName: "org.postgresql.Driver"
        jdbcURL: "jdbc:postgresql"
        host: "localhost"
        port: "5432"
        databaseName: "app"
        username: "cccat"
        password: "123456"
    hikari:
        maxPoolSize: 10
        autoCommit: "true"
